#pragma once
#include <conio.h>
#include <cmath>
#include <math.h>
#include <float.h>
#include <direct.h>
#include <string>
#include <ctime>    
#include <cstdlib>  
#include <stdio.h>
#include <iostream>
#include <fstream>
#include <stdlib.h>
#include <sstream>
#include "binary_trees.h"
#include "fuzzy_trees.h"
#include "fuzzy_c_trees.h"
#include "multidimensional_file.h"
#include "analysis_multidimensional.h"

